# Introduction to NumPy

## Installing & Updating the Package

NumPy comes pre-isntalled if you're using Anaconda. 
**pip install numpy** 

To get the latest version:
**pip install numpy --upgrade**

### Importing NumPy

In [1]:
import numpy as np

## We import packages libraries with "import name_of_packagge".
## Using "as np" is not mandatory. It's just common practice.
##conduct element wise operation

### Using NumPy

In [2]:
array_a = np.array([1,2,3])

## "np." -> Signals this is a NumPy function, since we imported the package as "np".
## np.array() creates an array with the values we input.
##scalar 0-d single value nd no bracket
##vector 1-d []
##matrix 2-d [[],[]]

In [3]:
array_a

## Displays the variable (unique to Jupyter).

array([1, 2, 3])

In [4]:
array_b = np.array([[1,2,3],[4,5,6]])
array_b

array([[1, 2, 3],
       [4, 5, 6]])

### NumPy Documentation

https://numpy.org/devdocs/ <- <i> A link to the NumPy documentation

In [5]:
np.mean(array_b, axis = 0)

## The np.mean() function takes an array and returns its algebraic mean.
## Axis 0 -> We're running this function over each column.
## shift+tab

array([2.5, 3.5, 4.5])

# Indexing

In [6]:
array_a = np.array([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
array_a[1]

## By adding numbers between square brackets, we can reference specific values of the array. 
## Python uses 0-indexing, so the first position has an index 0, the second position has index 1, and so on.

array([4, 5, 6])

In [8]:
array_a[1][0]

## We can index every dimension of the array separately.

4

In [9]:
array_a[1,0]

## [1,0] is equivalent to [1][0] 

4

In [10]:
array_a[:,0]

## The ":" is equivalent to "from start to end" in this context. 
## go throught all rows in the first column,interval index

array([1, 4])

# Negative Indices

In [11]:
array_b = np.array([1,2,3])
array_b[-1]

## Negative indices mean traversing from the back. 
## No such thing as  -0 , so the first negative index is -1
##-0 = 0

3

In [12]:
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
array_a[-1]

array([4, 5, 6])

In [15]:
# array_a[-3] 
# Goes out of bounds, since -3 implies there are 3 rows. 

In [16]:
array_a[:,-1]

array([3, 6])

# Assigning Values

In [17]:
array_a = np.array([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
array_a[0,2] = 9
array_a 

## Assign a value to an individual element.

array([[1, 2, 9],
       [4, 5, 6]])

In [19]:
array_a[0] = 9
array_a

## Assign a value to an entire row.

array([[9, 9, 9],
       [4, 5, 6]])

In [20]:
array_a[:,0] = 9
array_a

## Assign a value to an entire column.frst

array([[9, 9, 9],
       [9, 5, 6]])

In [21]:
list_a = [8,7,8] # this is 1 -d array without using array

array_a[0] = list_a
array_a

## Assign different values to an entire row via a list.can pass tuple also

array([[8, 7, 8],
       [9, 5, 6]])

In [22]:
type(array_a[0]) #only take the element ratherthan typr

numpy.ndarray

In [23]:
array_a[:] = 9
array_a

## Assign the same value to all the individual elements in the array.

array([[9, 9, 9],
       [9, 9, 9]])

In [24]:
array_a = 9
array_a

## Type assignment in Python is dynamic. Hence, a variable's type can change based on what values we assign to it. 
## Here, array_a changes from an ndarray to an integer.

9

In [25]:
type(array_a)

int

In [26]:
array_a = np.array([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

# Elementwise Properties

In [27]:
array_a = np.array([7,8,9])
array_a

array([7, 8, 9])

In [28]:
array_b = np.array([[1,2,3],[4,5,6]])
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
array_b * 2

## Multiplying each element of array_b by 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [30]:
list_a = [1,2,3]
list_a + [2]

## Since lists don't work elementwise, we're concatenating [2] to list_a.

[1, 2, 3, 2]

In [31]:
array_a + 2

## Elementwise addition adds 2 to each element of array_a.

array([ 9, 10, 11])

In [32]:
array_a * array_b[1]

## Elementwise multiplication. 
## We multiply each individual element of array_a by its corresponding element in the second row of array_b.not matrix mul

array([28, 40, 54])

In [33]:
array_b - array_a

## The order of the elements matters for elementwise subtraction, division, as well as other operations. 

array([[-6, -6, -6],
       [-3, -3, -3]])

In [37]:
array_b + array_a

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

# Types of Data Supported by NumPy

In [34]:
array_a = np.array([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
array_a = np.array([[1,2,3],[4,5,6]], dtype = np.float16)
array_a

# Defining all the values as floats (decimals).

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float16)

In [38]:
array_a = np.array([[1,2,3],[4,5,6]], dtype = np.complex64)
array_a

# Defining all the values as complex numbers.

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]], dtype=complex64)

In [39]:
array_a = np.array([[1,2,0],[4,5,6]], dtype = np.bool)
array_a

# Defining all the values as Booleans.
# T=rather than zero value

<ipython-input-39-d1909a485020>:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  array_a = np.array([[1,2,0],[4,5,6]], dtype = np.bool)


array([[ True,  True, False],
       [ True,  True,  True]])

In [40]:
array_a = np.array([[10,2,3],[4,5,6]], dtype = np.str)
array_a

# Defining all the values as text.
# u2 mean one of the element contain 2 chara

<ipython-input-40-e95068195692>:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  array_a = np.array([[10,2,3],[4,5,6]], dtype = np.str)


array([['10', '2', '3'],
       ['4', '5', '6']], dtype='<U2')

https://numpy.org/devdocs/reference/generated/numpy.dtype.kind.html <- A link to the documentation explaining the unicode abbreviation

# Characteristics of NumPy Functions

# Universal Functions

https://numpy.org/devdocs/reference/ufuncs.html <- A link to the documentation page on Universal Functions

Broadcasting

In [41]:
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

In [42]:
array_b = np.array([[1],[2]])
array_b

array([[1],
       [2]])

In [43]:
matrix_C = np.array([[1,2,3],[4,5,6]])
matrix_C

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
np.add(array_b, matrix_C)

## Adding up values, even though the arrays don't have matching shapes.both array have diifrent length and dim 
## ivide small matrix extend chyth big matrix athra aavum[[1,1,1],[2,2,2]] nd [[1,2,3],[1,2,3]], ippol ith randum c de shap aayi

array([[2, 3, 4],
       [6, 7, 8]])

# Type Casting

In [45]:
np.add(array_b, matrix_C, dtype = np.float64)

## We can define the datatyep
## ivide str koduthal error kaanikum bcz str cant do maths add operation

array([[2., 3., 4.],
       [6., 7., 8.]])

# Running over an Axis

In [46]:
np.mean(matrix_C, axis = 1)

## Axis = 0 runs the function over every column. 
## Axis = 1 runs the function over every row. 
## useful when large array have diff catg in diff colmn
## creat new array

array([2., 5.])

In [47]:
matrix_C 

array([[1, 2, 3],
       [4, 5, 6]])

# Working with Arrays

In [48]:
matrix_A = np.array([[1,2,3],[4,5,6]])
matrix_A

array([[1, 2, 3],
       [4, 5, 6]])

# Basic Slicing

In [49]:
matrix_A[:]

## The default start and stop for slicing are the origin and the end of the array. 
## Hence, [:] includes the entire array.consicutive

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
matrix_A[:,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
type(matrix_A[:,:])

## [:,:] -> All rows, and all columns.

numpy.ndarray

In [51]:
matrix_A[:2]

# [:2] -> All the rows up to the 3rd one (excluding the third one).

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
matrix_A[1]

array([4, 5, 6])

In [54]:
matrix_A[:-1]

# [:-1] -> All the rows up to the last one.

array([[1, 2, 3]])

In [60]:
matrix_A[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
matrix_A[2:]
## matrix_A[:n] nd matrix_A[n:] are compliment each other
## this 0-d
## indexing = specific idexing
## slicing = indervel indexing

array([], shape=(0, 3), dtype=int32)

In [55]:
matrix_A[:,1:]

# All the rows, but only the columns from the one with index 1 (second column) onwards.

array([[2, 3],
       [5, 6]])

In [64]:
matrix_A

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
matrix_A[1:,1:]

# All the rows after the first one and all the column after the first one. 

array([[5, 6]])

In [62]:
matrix_A[0]
## 1-d slice

array([1, 2, 3])

In [63]:
matrix_A[:1]
## 2d slicing

array([[1, 2, 3]])

# Stepwise Slicing

In [65]:
matrix_B = np.array([[1,1,1,2,0], [3,6,6,7,4], [4,5,3,8,0]])
matrix_B
## dont have consicutive value
## step element can be posi or neg ,not zero

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [66]:
matrix_B[-1::-1,::2]

# The syntax for each dimension is "[start : stop : step]". 
# A negative step means we're going through the array in reverse.

array([[4, 3, 0],
       [3, 6, 4],
       [1, 1, 0]])

In [67]:
matrix_B[::,::2]

array([[1, 1, 0],
       [3, 6, 4],
       [4, 3, 0]])

# Conditional Slicing

In [68]:
matrix_C = np.array([[1,1,1,2,0], [3,6,6,7,4], [4,5,3,8,0]])
matrix_C

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [69]:
matrix_C[:,0]

array([1, 3, 4])

In [70]:
matrix_C[:,0] > 2

# Returns True/False based on whether the individual element satisfies the condition. 

array([False,  True,  True])

In [71]:
matrix_C[:,:] > 2

# Returns True/False based on whether the individual element satisfies the condition. 

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False]])

In [72]:
matrix_C[matrix_C[:,:] % 2 == 0]

# Returns the actual values which satisfy the condition, not simply True or False.

array([2, 0, 6, 6, 4, 4, 8, 0])

In [73]:
matrix_C[(matrix_C[:,:] % 2 == 0) | (matrix_C[:,:] <= 4)]

# We can have more complex conditions, which are comprised of several smaller conditions. 
# & -> Both conditions must be met. 
# | -> Either condition can be met. 

array([1, 1, 1, 2, 0, 3, 6, 6, 4, 4, 3, 8, 0])

# Dimensions and the Squeeze Function

In [74]:
matrix_D = np.array([[1,1,1,2,0], [3,6,6,7,4], [4,5,3,8,0]])
matrix_D

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [75]:
type(matrix_D[0,0])

# Fixing both indices. 
# 0-D array
## got int

numpy.int32

In [76]:
print(matrix_D[0,0])

1


In [77]:
type(matrix_D[0,0:1])

# 1 index is fixed, the second one is a slice
# 1-D array
## got arrayn , have [] , 1-d array

numpy.ndarray

In [78]:
print(matrix_D[0,0:1])

[1]


In [79]:
type(matrix_D[0:1,0:1])

# Both indices are ranges (slices)
# 2-D array

numpy.ndarray

In [80]:
print(matrix_D[0:1,0:1])
## 2-d array, matrix

[[1]]


In [81]:
print(matrix_D[0,0].shape)
print(matrix_D[0,0:1].shape)
print(matrix_D[0:1,0:1].shape)

# Same value stored in 3 different ways -> 0-D, 1-D and 2-D array
## ethil store cheyyum?

()
(1,)
(1, 1)


In [82]:
print(matrix_D[0:1,0:1].squeeze())

## Removes excess dimensions

1


In [88]:
np.squeeze(matrix_D[0:1,0:1])

## The function is equivalent to the method. 

array(1)

In [89]:
print(matrix_D[0,0].squeeze().shape)
print(matrix_D[0,0:1].squeeze().shape)
print(matrix_D[0:1,0:1].squeeze().shape)

## All excess dimensions are lost and our outputs are aligned.
## squeez alwys use before shape

()
()
()


In [90]:
matrix_D[0:1,0:1].squeeze()
# both are same, this is methord
# apply squeez we can use any slicing variation to get same chunk of data

array(1)

# Generating Data w/ Numpy

# np.empty(), np.zeros(), np.ones(), np.full()

In [2]:
import numpy as np

In [4]:
array_empty = np.empty()

TypeError: empty() missing required argument 'shape' (pos 1)

In [5]:
array_empty = np.empty(shape = (2,3))
array_empty
## create empty array
##return array without initializing entries
## fastest way to generate n-d array
##usful for testing and filling missing value

array([[1.235e-321, 0.000e+000, 0.000e+000],
       [0.000e+000, 0.000e+000, 0.000e+000]])

In [6]:
# zeros
array_0s = np.zeros(shape  = (2,3))
array_0s

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
array_0s = np.zeros(shape = (2,3), dtype = np.int8) 
array_0s
##specify data type

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [8]:
# ones
array_1s = np.ones(shape  = (2,3))
array_1s

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
# full
array_full = np.full(shape = (2,3), fill_value = 2) # One additional mandatory argument - fill_value -> scalar,can have both numb and test
array_full

array([[2, 2, 2],
       [2, 2, 2]])

In [10]:
array_full = np.full(shape = (2,3), fill_value = 'Three-Six-Five')
array_full

array([['Three-Six-Five', 'Three-Six-Five', 'Three-Six-Five'],
       ['Three-Six-Five', 'Three-Six-Five', 'Three-Six-Five']],
      dtype='<U14')

# "_like" functions

In [12]:
matrix_A = np.array([[1,0,9,2,2],[3,23,4,5,1],[0,2,3,4,1]])
matrix_A
##covenient when working with large data base
##like array westore a value or each element of orginal one

array([[ 1,  0,  9,  2,  2],
       [ 3, 23,  4,  5,  1],
       [ 0,  2,  3,  4,  1]])

In [13]:
array_empty_like = np.empty_like(matrix_A)    

# Shape and type are like the prototype. 
# If we want to override this, we can define dtype and shape and pass different values (but why even use empty_like then). 
# dont need to specify the shape or type, take shape od matrix a

array_empty_like

array([[    227,       0,       0,       0,       0],
       [      0,       0,       0,       0,       0],
       [    812,       0,       0, 6029363,       0]])

In [14]:
array_0s_like = np.zeros_like(matrix_A)    
array_0s_like

# We have corresponding functions for 1s and full as well.
# We have corresponding functions for 1s and full as well. 
# can use as starting point
# can use as switch where values change frome o to 1 and vicversa
# useful when working with dummy variable

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [17]:
array_1s_like = np.full_like(matrix_A)    
array_1s_like

TypeError: _full_like_dispatcher() missing 1 required positional argument: 'fill_value'

# np.arange()

In [18]:
#range(30)
list(range(30))

# range(30) results in a range object.
# list(range(30)) creates a list with all the values in this range.

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29]

In [19]:
array_rng = np.arange(30)
array_rng

## Creates an ndarray with the values in this range.non random value
## consecutive valur
## range give range object
## array range give array object

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [20]:
# array_rng = np.arange(stop =  30)
array_rng = np.arange(start =  30)
array_rng

# The only mandatory argument is "start", rather than stop. 
# If we specify only a start, the function assumes this is the "stop" and starts from the origin (0)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [21]:
array_rng = np.arange(start = 0, stop =  30)
array_rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [22]:
array_rng = np.arange(start = 0, stop =  30, step = 2.5)
array_rng

# "Step" doesn't have to be the same type as the values of the array. 

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5, 25. ,
       27.5])

In [23]:
array_rng = np.arange(start = 0, stop =  30, step = 2.5, dtype = np.float32)
array_rng = np.arange(start = 0, stop =  30, step = 2.5, dtype = np.int32)
array_rng

# The casting happens after all the computations. 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

# Random Generators

# Defining Random Generators

In [24]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg


## We load two functions from the numpy.random module.
## diif way to generate random variable
## generator functin takes a bit generator as an input and create a generator object, those object are instance of numpy generatoe class
## numpy .random .generator class
##pcg=permutation congruential genertor, function pointer that can produce value of upto 64 bit in size

In [26]:
array_RG = gen(pcg())

#array_RG.normal()
#array_RG.normal(size = 5)
array_RG.normal(size = (5,5))

# RG is short for Random Generator.
## norma funtion generate randome variable and from random distribution
## can have scalar single value,get diffrent op in each excution

array([[-0.80190825,  0.20020152, -0.95099679, -0.30167788,  1.31115589],
       [-0.2458983 ,  0.77784115, -0.40306798, -0.1199499 , -0.01880679],
       [ 0.0162525 , -0.51997882,  0.75029501,  2.63459716, -0.10913986],
       [ 0.14185979,  0.78733914, -0.59984311,  1.88163931, -0.95522804],
       [ 2.07915411,  1.15592274,  0.50716451,  1.34728749, -1.250233  ]])

We can set a seed, so that our random values don't change everytime we re-run the code. We'll se the seed equal to 365

In [27]:
array_RG = gen(pcg(seed = 365)) 
array_RG.normal(size = (5,5))

# Re-running this cell provides a consistent output, since the seed (with fixed starting values) is set.

array([[-0.13640899,  0.09414431, -0.06300442,  1.05391641, -0.6866818 ],
       [-0.50922173, -0.7999526 ,  0.73041825,  0.08825439, -2.1177576 ],
       [ 0.65526774, -0.48095012, -0.5519114 , -0.58578662, -0.98257896],
       [ 1.12378166, -1.30984316, -0.04703774,  0.955272  ,  0.26071745],
       [-0.20023668, -1.50172484, -1.4929163 ,  0.96535084,  1.18694633]])

In [28]:
array_RG.normal(size = (5,5))

# The seed is fixed for a single itteration. 
## whenvwer want apom seed pinheyum ezhuthanam

array([[-0.76065577,  1.48158358,  0.01200258, -0.06846959,  0.25301664],
       [-0.52640788,  0.79613109,  0.28203421,  1.80238008,  0.93932117],
       [-0.53693283, -0.26317689, -1.77723035,  1.14900013, -2.20733915],
       [ 1.54116775, -0.5124932 , -2.14564563,  1.98878673,  0.32208907],
       [-1.2651495 ,  3.2714633 ,  1.78650493, -0.20233675,  0.20427467]])

# Generating Integers, Probabilities and Random Choices

other way of generating random variable

# nmpy.int

In [29]:
array_RG = gen(pcg(seed = 365)) 
#array_RG.integers(10, size = (5,5))
array_RG.integers(low = 10, high = 100, size = (5,5))

# Generates integers within a range
# Generates whole integers within a range.
## requrd fixed range
## if provide single value it assume only want integer from 0 to that range

array([[18, 78, 64, 78, 84],
       [66, 67, 28, 10, 69],
       [45, 15, 37, 74, 96],
       [19, 21, 89, 73, 54],
       [53, 84, 66, 51, 92]], dtype=int64)

In [30]:
array_RG = gen(pcg(seed = 365)) 
#array_RG.integers(10, size = (5,5))
array_RG.integers(10, size = (5,5))

array([[0, 7, 6, 7, 8],
       [6, 6, 2, 0, 6],
       [3, 0, 3, 7, 9],
       [1, 1, 8, 7, 4],
       [4, 8, 6, 4, 9]], dtype=int64)

# prob distrbtion

In [31]:
array_RG = gen(pcg(seed = 365)) 
array_RG.random(size = (5,5))
## get value of contines random distribution bw 0 nd 1

array([[0.75915734, 0.7662218 , 0.6291028 , 0.20336599, 0.66501486],
       [0.06559111, 0.71326309, 0.10812106, 0.87969046, 0.49405844],
       [0.82472673, 0.45652944, 0.07367232, 0.69628564, 0.36690736],
       [0.29787156, 0.4996155 , 0.4865245 , 0.62740703, 0.54952637],
       [0.64894629, 0.04411757, 0.7206516 , 0.84594003, 0.17159792]])

In [35]:
array_RG.choice(matrix_A[0], size = (5,5))

array([[2, 2, 2, 0, 2],
       [9, 0, 2, 2, 0],
       [0, 0, 1, 9, 9],
       [9, 1, 0, 9, 2],
       [1, 2, 9, 1, 9]])

In [33]:
#array_RG.choice(matrix_A[0], size = (5,5))
array_RG = gen(pcg(seed = 365)) 
array_RG.choice([1,2,3,4,5], size = (5,5))
# ivide fixed prob nalkiyittilla,so discrete distribution aan ivide ,default

array([[1, 4, 4, 4, 5],
       [4, 4, 2, 1, 4],
       [2, 1, 2, 4, 5],
       [1, 1, 5, 4, 3],
       [3, 5, 4, 3, 5]])

In [34]:
#array_RG.choice(matrix_A[0], size = (5,5))
array_RG = gen(pcg(seed = 365)) 
#array_RG.choice([1,2,3,4,5], size = (5,5))
array_RG.choice((1,2,3,4,5), p = [0.1,0.1,0.1,0.1,0.6],size = (5,5))

# Chooses among a given set (with possible weighted probabilities).
## ivide fixed prob nalkiyittund
## size same aayirikanam elemewnt in choice= element in p

array([[5, 5, 5, 3, 5],
       [1, 5, 2, 5, 5],
       [5, 5, 1, 5, 4],
       [3, 5, 5, 5, 5],
       [5, 1, 5, 5, 2]])

# Generating Arrays From Known Distributions

In [36]:
array_RG = gen(pcg(seed = 365)) 
array_RG.poisson(size = (5,5))

# The default Poisson distribution
## pison dist mena o er  afixed ibtervel of tme ,distance or space expect an event occure exact once
# here lamda 1, lamda maatiyal get ovr fixed intervel time get exact morthan same same occurance

array([[2, 0, 1, 1, 2],
       [1, 1, 0, 1, 1],
       [1, 2, 1, 1, 0],
       [0, 1, 0, 2, 1],
       [0, 1, 0, 0, 2]], dtype=int64)

In [37]:
array_RG = gen(pcg(seed = 365)) 
array_RG.poisson(lam = 10,size = (5,5))

# Specifying lambda. 

array([[11, 12, 12, 14, 13],
       [ 9, 10, 11, 11,  8],
       [11,  8, 10,  9, 14],
       [ 7,  8,  9, 15, 15],
       [13,  8,  8,  7,  9]], dtype=int64)

In [38]:
array_RG = gen(pcg(seed = 365)) 
array_RG.binomial(n = 100, p = 0.4, size = (5,5))

# A binomial distribution with p = 0.4 and 100 trials. 
## measure howmany time a certain outcome can appear over a series of trial. where there are only two possible value
#ivide kanikkunna number is the number of time out of 100 we have gooten orefred outcome
## on avg most outcome bw 38 and 50 so avg is 40, it mean 40 per probalty of getting what we want on each of 100 individual trial

array([[42, 44, 30, 36, 45],
       [36, 41, 38, 42, 41],
       [35, 31, 35, 46, 29],
       [41, 41, 46, 34, 48],
       [45, 45, 45, 40, 43]], dtype=int64)

In [39]:
array_RG = gen(pcg(seed = 365)) 
array_RG.logistic(loc = 9, scale = 1.2, size = (5,5))

# A logistic distribution with a location = 9 and scale = 1.2.
## each element is the possible outcome of logistic regresion

array([[10.37767822, 10.42451863,  9.63404367,  7.36153427,  9.82286787],
       [ 5.81223125, 10.09354231,  6.46790532, 11.38740256,  8.97147918],
       [10.85844698,  8.79081317,  5.962079  ,  9.99560681,  8.34539118],
       [ 7.97105522,  8.9981544 ,  8.93530194,  9.6253307 ,  9.23850869],
       [ 9.73729284,  5.3090678 , 10.13723528, 11.04372782,  7.11078651]])

# Applications of Random Generators

Creating Tests

In [40]:
array_RG = gen(pcg(seed = 365)) 

array_column_1 = array_RG.normal(loc = 2, scale = 3, size = (1000))
array_column_2 = array_RG.normal(loc = 7, scale = 2, size = (1000))
array_column_3 = array_RG.logistic(loc = 11, scale = 3, size = (1000))
array_column_4  = array_RG.exponential(scale = 4, size = (1000))
array_column_5  = array_RG.geometric(p = 0.7, size = (1000))

# Create the individual columns of the dataset we're creating. 
##when real data isnt avialable need psudo random data to test how well the program work
## can use any ditbtion or artribute but size shoulld be same

In [47]:
#random_test_data = np.array([array_column_1, array_column_2, array_column_3, array_column_4, array_column_5]).transpose()
random_test_data = np.array([array_column_1, array_column_2, array_column_3, array_column_4, array_column_5]).transpose()
random_test_data

# Use np.array to generate a new array with the 5 arrays we created earlier. 
# Use the transpose method to make sure our dataset isn't flipped. 

array([[ 1.59077303,  6.42174295, 10.14698427,  6.91500737,  1.        ],
       [ 2.28243293,  8.57902322, 15.93309953,  6.243605  ,  1.        ],
       [ 1.81098674,  5.17270135, -0.46878789,  2.44997251,  1.        ],
       ...,
       [ 0.1973629 ,  4.3465854 ,  2.66485989,  0.80935387,  1.        ],
       [-2.21015722,  8.2176402 , 12.69328115,  0.50644607,  2.        ],
       [ 2.91161235,  7.90337695, 11.79840961,  4.86816939,  1.        ]])

In [42]:
random_test_data.shape

(1000, 5)

In [43]:
np.savetxt("Random-Test-from-NumPy.csv", random_test_data, fmt = '%s', delimiter = ',')


# Saving the arrays to an extrenal file we're creating. 

# file name -> "Random-Test-from-NumPy.csv"
# random_test_data -> data we're exporting (saving to an external file)
# format -> strings
# delimiter ","

# We'll talk more about these in just a bit. 

In [44]:
np.genfromtxt("Random-Test-from-NumPy.csv", delimiter = ',')

# Importing the data from the file we just created.

array([[ 1.59077303,  6.42174295, 10.14698427,  6.91500737,  1.        ],
       [ 2.28243293,  8.57902322, 15.93309953,  6.243605  ,  1.        ],
       [ 1.81098674,  5.17270135, -0.46878789,  2.44997251,  1.        ],
       ...,
       [ 0.1973629 ,  4.3465854 ,  2.66485989,  0.80935387,  1.        ],
       [-2.21015722,  8.2176402 , 12.69328115,  0.50644607,  2.        ],
       [ 2.91161235,  7.90337695, 11.79840961,  4.86816939,  1.        ]])

In [45]:
rand_test_data = np.genfromtxt("Random-Test-from-NumPy.csv", delimiter = ',')
print(rand_test_data)
## print or just call variabl use chythum op display cheyyam

[[ 1.59077303  6.42174295 10.14698427  6.91500737  1.        ]
 [ 2.28243293  8.57902322 15.93309953  6.243605    1.        ]
 [ 1.81098674  5.17270135 -0.46878789  2.44997251  1.        ]
 ...
 [ 0.1973629   4.3465854   2.66485989  0.80935387  1.        ]
 [-2.21015722  8.2176402  12.69328115  0.50644607  2.        ]
 [ 2.91161235  7.90337695 11.79840961  4.86816939  1.        ]]


# Importing Data with NumPy

# np.loadtxt() vs np.genfromtxt()

In [2]:
import numpy as np

In [3]:
lending_co_data_numeric_1 = np.loadtxt("Lending-Company-Numeric-Data.csv", delimiter = ',')
lending_co_data_numeric_1

# We can use Notepad++ to determine delimiters

OSError: Lending-Company-Numeric-Data.csv not found.